# Generated by Django 3.2.5 on 2021-08-02 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_addpost_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpost',
            name='post_image',
        ),
        migrations.AddField(
            model_name='addpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 3, 1, 4, 37, 949397)),
        ),
    ]
