# Generated by Django 3.2.5 on 2021-08-04 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20210804_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcomment',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 4, 16, 33, 9, 935874)),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 4, 16, 33, 9, 935874)),
        ),
    ]
