# Generated by Django 3.2.5 on 2021-08-04 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20210804_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 4, 23, 58, 49, 228408)),
        ),
        migrations.DeleteModel(
            name='AddComment',
        ),
    ]
