# Generated by Django 3.2.5 on 2021-08-24 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20210804_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True, null=True)),
                ('sub_body', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2021, 8, 24, 21, 12, 12, 610555))),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='addcomment',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 24, 21, 12, 12, 610555)),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 24, 21, 12, 12, 610555)),
        ),
    ]
